wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719503977
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.12.4
      5: 0.17.3
      8:
      - 5
      13: linux-x86_64
architecture:
  desc: null
  value: '3 layers, ins: 2, 64, 64 | sum x and t'
sampler:
  desc: null
  value: ema_model
noise_time_steps:
  desc: null
  value: 128
time_dim_embedding:
  desc: null
  value: 64
epochs:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.001
cfg_strength:
  desc: null
  value: 3.0
beta_ema:
  desc: null
  value: 0.999
samples:
  desc: null
  value: 1000
num_classes:
  desc: null
  value: 2
