wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719993479
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.12.4
      5: 0.17.3
      8:
      - 5
      13: linux-x86_64
architecture:
  desc: null
  value: '5 layers, ins: 92, 2*92, 3*92, 2*92, 92 | concat x and t'
sampler:
  desc: null
  value: ema_model
noise_time_steps:
  desc: null
  value: 256
time_dim_embedding:
  desc: null
  value: 64
epochs:
  desc: null
  value: 64
scheduler:
  desc: null
  value: linear
learning_rate:
  desc: null
  value: 0.001
beta_ema:
  desc: null
  value: 0.999
samples:
  desc: null
  value: 1000
